# Generated by Django 6.1 on 2026-09-26 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('slug', models.SlugField(max_length=10, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('entradas', 'Entradas'), ('principais', 'Pratos Principais'), ('sobremesas', 'Sobremesas'), ('bebidas', 'Bebidas'), ('drinks', 'Drinks')], max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('esgotado', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['categoria', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('preparando', 'Preparando'), ('pronto', 'Pronto')], default='recebido', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('excluido', models.BooleanField(default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.itemcardapio')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('horario', models.CharField(max_length=5)),
                ('pessoas', models.CharField(max_length=20)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('excluido', models.BooleanField(default=False)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['data', 'horario'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('excluido', False)), fields=('data', 'horario'), name='reserva_unica_por_horario_ativo')],
            },
        ),
    ]
