# Generated by Django 6.1 on 2026-09-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcardapio',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='cardapio/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('mesa', 'Consumo no restaurante'), ('retirada', 'Retirada no local'), ('entrega', 'Entrega em casa')], default='mesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
